services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/db-init:/docker-entrypoint-initdb.d
    networks:
      - default

  server:
    container_name: python_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    networks:
      - default

  client:
    container_name: nextjs_client
    build:
      context: ./client
      target: dev
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.local
    restart: always
    volumes:
      - ./client:/app
      - ./client/public:/app/public
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - default

networks:
  default:
    name: ai-complaint-analysis
    driver: bridge

volumes:
  pgdata: